---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - set_fact: wtf_dir="{{external_extra_var}}/dynamically_defined_dir"
    - include_tasks: "{{wtf_dir}}/roles/role2/tasks/main.yml"  
    # - include_role: name="{{wtf_dir}}/roles/role2" # ERROR! 'wtf_dir' is undefined  
    #   static: no
#- import_playbook: "{{external_extra_var}}/dynamically_defined_dir/do.yml"  # OK, can use external extra vars
# - import_playbook: "{{wtf_dir}}/do.yml"  # ERROR! 'wtf_dir' is undefined  

